### ISSUE TITLE
 Voice messages crash the app

### ISSUE THREAD

**Issue by tyuby** [oxen-io/session-android#507]
There is a long-standing stable bug with voice messages.

When you try to receive or send a voice message by the app, even if it is 1-second long, the app crashes irrevocably. After that, only uninstalling the app and installing it again helps.

Tested on Android 5, 6, 6, 7, 7, 10. The bug appears on four out of six devices (5, 6, 6, 7). The bug has been observed on all releases since 1.6.7 at least.

I did not catch any pattern, but it seems that the bug does not appear on more powerful devices.

**Comment by nielsandriesse** [comment]
Hi @tyuby, I believe this is fixed on the latest version of Session (1.10.7). Could you please confirm and close this issue if it no longer happens?

**Comment by tyuby** [comment]
Unfortunately, the bug still remains. With every new release I check this point, 1.10.8 - any voice message still crashes the app on one of my tablets. Android 6.0 / Huawei BG2-W09.

**Comment by tyuby** [comment]
The problem was fixed in 1.11.0.
Now I and my friends can not only write text messages but also send voice messages.
