### ISSUE TITLE
Session jumps while reading messages

### ISSUE THREAD

**Issue by noghx** [oxen-io/session-android#579]
Session jumps while im reading through the open group messages.

I think this always happens when a new message arrives.

**Comment by nielsandriesse** [comment]
We're currently in the process of rebuilding the conversation screen, which should fix this as well.

**Comment by KeeJef** [comment]
This issue looks like its resolved, but please reopen if still occurring
