### ISSUE TITLE
Session crushes when trying to send pictures from built in gallery

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#609]

**Comment by Flam3z** [comment]
can repo

version: 1.10.13
Device: Galaxy S10 | Android 11 | One UI 3.0

**Comment by nielsandriesse** [comment]
This should be fixed on 1.11.0

**Comment by Flam3z** [comment]
Update: on 1.11.0 the app still crashes when i attempt the same steps

**Comment by Flam3z** [comment]
@nielsandriesse may this be re-opened?

**Comment by User1l0** [comment]
Same here, session is still crushing, it can't handle heavy amounts of pictures from gallery

**Comment by hjubb** [comment]
I believe this is fixed in 1.11.8, let me know if this is not the case
