### ISSUE TITLE
Notifications in slow mode don't show up until app is focused

### ISSUE THREAD

**Issue by Para-lyzed** [oxen-io/session-android#921]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When using "slow mode" for notifications, I don't receive notifications from new messages until I open the Session app.

EDIT: ~~Issue also exists in fast mode according to [SisyphusRising](https://github.com/oxen-io/session-android/issues/921#issuecomment-1172841780).~~ User has de-googled ROM, so that behavior is expected.

**To reproduce**

1. Create a new Session ID on latest version of app.
2. Select "slow mode" (or apparently also fast mode) for notifications.
3. Use another device to message new account and accept the request.
4. Send messages while Session Android user does not have the app open (open as in focused; the app is not force stopped, killed by the system, and stays open in the Recents tab).
5. Never receive a notification until opening the Session app.

**Smartphone (please complete the following information):**

 - Device: OnePlus 7 Pro
 - OS: Android 11 on LineageOS 18.1 (lineage-18.1-20220626-nightly-guacamole)
 - Session F-Droid 1.13.6 (official repo *and* unofficial F-Droid build without FCM)

**Additional context**

I have never used Session before this update, so I do not know if this worked properly before, or if it may be a bug affecting accounts created during this patch. I use a VPN (ProtonVPN *without* malware/tracker/ad blocking), but this behavior has been observed while not connected. I *do* have Gapps, but I do not want to use notifications through Google's FCM, so I have not tried the "fast" notifications from the other versions of the app (though I have tried slow mode on the Session F-Droid repo where Google FCM is still integrated and had the same issue). Notifications are enabled in app and in Android settings, and battery optimization has been turned off as to not kill Session in the background. When I open the app any time after receiving a new message, the notification pops up and the message shows up in my list. I have waited multiple hours to make sure that it wasn't just a really slow polling rate, but anything more than a few minutes would be pretty ridiculous for a messaging app anyway. I am rooted, but that should not matter as I am not granting root permissions to any apps (about to move away from rooting and to a degoogled ROM). I have tried reinstalling, creating a new Session ID, rebooting my phone, clearing cache, essentially everything I could think of. I have not included any logs, as this takes place over such a long amount of time that digging through an hour or more of a logcat output would be ridiculous. I *would* like to ask what the default polling rate is, so I know what I should expect. Please let me know if you're unable to reproduce this, as I don't have another phone to try it on.

EDIT: It seems to work fine in Session version 1.13.0 off the F-Droid repo, though it seems to only poll once every 15 minutes.

**Comment by SisyphusRising** [comment]
I'm experiencing the same issues with notifications never appearing until I open the app. Likewise have seen messages that were sent to me hours ago finally appear as a notification, but only when I finally open the app.
I have also tried clearing cache and reinstalling but no luck.
I have it in "fast mode" as well.

I'm running GrapheneOS and using MullvadVPN.

**Comment by Para-lyzed** [comment]
> I have it in "fast mode" as well.

Good to know, I guess it isn't just limited to "slow mode" without Google FCM then. If you can confirm that I'll update the title and include that in the bug report.

**Comment by SisyphusRising** [comment]
Can confirm this is happening for me on both fast mode and slow mode. No notifications until I open the app. Also adding that my phone is a Pixel 5 if that helps at all.

**Comment by hjubb** [comment]
Thanks for the report, I'll take a look to see what could be causing this. Just to confirm, are either of you using "fast mode" with a de-googled ROM? The "fast mode" works exclusively on FCM so if it's not available it will not matter if you have fast or slow mode and will just use the slow mode. Either way I'll investigate the background polling and see if there is some issue there. Will let you know what I come across / when to expect a fix

**Comment by SisyphusRising** [comment]
Yes, I'm using a de-googled ROM (GrapheneOS).  

Does that mean I also will never get notifications without "fast mode"/FCM? Or does "fast mode"/FCM only effect the speed of recieving notifications? As of now I get no notifications, period, until I open the app. Thanks for the response.

**Comment by Para-lyzed** [comment]
> Just to confirm, are either of you using "fast mode" with a de-googled ROM?

I am not on a de-googled ROM, and I am using slow mode. I have not tried fast mode, but given that @SisyphusRising is using fast mode on a de-googled ROM, I will remove the "fast mode" part of the issue because that is expected behavior. I had mistakenly assumed they were using sandboxed play services when they commented that they were using GrapheneOS.

Just to confirm, are you using sandboxed play services SisyphusRising?

**Comment by SisyphusRising** [comment]
> Just to confirm, are you using sandboxed play services SisyphusRising?

No, I am not using sandboxed play services

**Comment by hjubb** [comment]
> Does that mean I also will never get notifications without "fast mode"/FCM? Or does "fast mode"/FCM only effect the speed of recieving notifications? As of now I get no notifications, period, until I open the app. Thanks for the response.

The fast mode will just try to use FCM if it's available, even as it stands there is currently no way to get pushed notifications from open group servers for instance, so fast mode will basically be FCM notifications + everything that slow mode should give you which is periodic background polling. I'll try to fix any slow mode specific issues to see if that fixes the problem you are encountering

**Comment by hjubb** [comment]
This should be fixed by #925, once we test it doesn't break anything and merge it, it should be in the next release shortly after

**Comment by Para-lyzed** [comment]
Closing, as this has been fixed by #925. Polling period is still 15 minutes though, so I hope that #924 is added at some point in the future.

**Comment by hjubb** [comment]
Thanks, sorry I may have missed this issue when closing the other as being fixed!

**Comment by dFr3sh** [comment]
Seems like this is still an issue, but for closed groups. Same steps to reproduce basically, but closed group created from "Create Group" instead of a single contact. GrapheneOS on Pixel 7 running version 1.16.3 from the official Fdroid repo. No sandboxed Google, slow mode. Notifications only show up when app is refocused. Tried unrestricted battery usage for the app and urned off "Pause app activity if unused" but the issue persists. Pretty consistent if not all the time. Seems like the polling is just not running.

**Comment by Para-lyzed** [comment]
@dFr3sh I recommend opening a new issue, as yours seems to be much more specific than this one and from a different version. Also note that the polling frequency for slow mode is 15 minutes. If you are not waiting 15 minutes for the notification to show up, then this is expected behavior.

**Comment by dFr3sh** [comment]
@Para-lyzed will do, thanks.
